// Package registrar provides an HTTP API for domain registration on AltNet.
//
// This is the registration backend that runs alongside the local AltNet
// daemon. The AltNet desktop app (and later a browser extension for
// visitor-only nodes) calls these endpoints over localhost to check
// availability, register new domains, update where they point, and list
// registered domains.
//
// All mutating endpoints require a bearer token in the Authorization
// header. The token is generated by the local app and only it knows the
// value, so attackers who scan localhost ports cannot register domains
// through someone else's daemon.
//
// Typical flow (driven by the AltNet app UI):
//
//  1. User opens AltNet, picks "Register a domain", types "alice.alt"
//  2. App calls GET /api/check/alice.alt -> {"available":true}
//  3. App calls POST /api/register with name + content root + owner
//  4. Registrar publishes a signed NameRecord to the DHT
//  5. alice.alt is now live on AltNet and reachable from any node
//
// The NameRecord is signed by this node's Ed25519 identity. Future
// updates to the same name require the same identity, so an account
// (= keypair) effectively owns its registered names.
//
// First-store-wins squatting at the protocol level is still possible:
// nothing here prevents someone else racing to publish "alice.alt" first
// from their own node. A global anti-squatting mechanism (reputation,
// proof-of-personhood, or a blockchain registry) is future work; for
// now, the social cost of squatting in a small network and the AltNet
// app's UX are the only deterrents.
package registrar

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"altnet/apps/files"
	"altnet/apps/sitestats"
	"altnet/core/crypto"
	"altnet/core/dht"
	"altnet/core/name"
)

// Registrar is the HTTP API server for domain management.
type Registrar struct {
	d     *dht.DHT
	id    *crypto.Identity
	token string // bearer token for authentication

	// registry tracks domains we've registered. Backed by a JSON file
	// at registryPath when persistence is enabled.
	mu           sync.RWMutex
	registry     map[string]*RegistrationRecord // canonical name -> record
	registryPath string                         // empty = in-memory only

	// stats is optional; if set, the registrar can expose per-site
	// analytics through its API for the desktop dashboard.
	stats sitestats.Reader
}

// SetStats wires a stats reader. Call before Start.
func (reg *Registrar) SetStats(s sitestats.Reader) { reg.stats = s }

// RegistrationRecord tracks a registered domain.
type RegistrationRecord struct {
	Name        string `json:"name"`         // canonical domain name
	Root        string `json:"root"`         // hex content key it points to
	Owner       string `json:"owner"`        // account identifier from panmox.org
	RegisteredAt int64 `json:"registered_at"` // unix timestamp
	UpdatedAt   int64  `json:"updated_at"`   // unix timestamp of last update
	Version     int64  `json:"version"`       // monotonically increasing
}

// New creates an in-memory Registrar. The token is used to authenticate
// API requests from your website backend. The DHT and identity are used
// to publish NameRecords.
//
// Use NewWithDataDir to persist the domain registry across restarts.
func New(d *dht.DHT, id *crypto.Identity, token string) *Registrar {
	return &Registrar{
		d:        d,
		id:       id,
		token:    token,
		registry: make(map[string]*RegistrationRecord),
	}
}

// NewWithDataDir creates a Registrar whose domain registry is persisted
// to <dataDir>/registrar.json. If the file already exists from a
// previous run, it is loaded so registrations survive restarts.
//
// Persistence is critical for the registrar: the per-registration owner
// info (account ID, registration timestamp) lives only here, NOT in the
// DHT NameRecord, so without persistence we'd lose the link between a
// domain and the account that owns it on every restart.
func NewWithDataDir(d *dht.DHT, id *crypto.Identity, token, dataDir string) (*Registrar, error) {
	r := &Registrar{
		d:        d,
		id:       id,
		token:    token,
		registry: make(map[string]*RegistrationRecord),
	}
	if dataDir != "" {
		if err := os.MkdirAll(dataDir, 0o700); err != nil {
			return nil, fmt.Errorf("create registrar data dir: %w", err)
		}
		r.registryPath = filepath.Join(dataDir, "registrar.json")
		if err := r.load(); err != nil {
			return nil, fmt.Errorf("load registrar registry: %w", err)
		}
	}
	return r, nil
}

// load reads the registry file from disk. Missing file is fine -- we
// just start with an empty registry. Corrupt file is an error.
func (reg *Registrar) load() error {
	data, err := os.ReadFile(reg.registryPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if len(data) == 0 {
		return nil
	}
	var stored map[string]*RegistrationRecord
	if err := json.Unmarshal(data, &stored); err != nil {
		return fmt.Errorf("parse registrar.json: %w", err)
	}
	reg.registry = stored
	return nil
}

// save writes the registry to disk atomically. Caller must hold reg.mu.
// Best-effort: on disk errors we keep the in-memory state and log so the
// registrar continues to serve requests.
func (reg *Registrar) save() {
	if reg.registryPath == "" {
		return // in-memory only
	}
	data, err := json.MarshalIndent(reg.registry, "", "  ")
	if err != nil {
		slog.Warn("registrar: marshal registry failed",
			"subsystem", "registrar", "err", err)
		return
	}
	tmp := reg.registryPath + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		slog.Warn("registrar: write registry tmp failed",
			"subsystem", "registrar", "err", err)
		return
	}
	if err := os.Rename(tmp, reg.registryPath); err != nil {
		slog.Warn("registrar: rename registry failed",
			"subsystem", "registrar", "err", err)
		os.Remove(tmp)
	}
}

// Start begins listening on addr. Returns the http.Server so the caller
// can shut it down later.
func (reg *Registrar) Start(addr string) (*http.Server, error) {
	mux := http.NewServeMux()
	mux.HandleFunc("/api/check/", reg.handleCheck)
	mux.HandleFunc("/api/register", reg.handleRegister)
	mux.HandleFunc("/api/update", reg.handleUpdate)
	mux.HandleFunc("/api/domains", reg.handleDomains)
	mux.HandleFunc("/api/publish", reg.handlePublish)
	mux.HandleFunc("/api/revoke", reg.handleRevoke)
	mux.HandleFunc("/api/stats/", reg.handleStats)
	mux.HandleFunc("/api/unregister", reg.handleUnregister)
	srv := &http.Server{
		Addr:              addr,
		Handler:           corsMiddleware(mux),
		ReadHeaderTimeout: 5 * time.Second,
	}
	go func() {
		_ = srv.ListenAndServe()
	}()
	// Background re-anchor loop: every locally-registered .alt name has
	// its NameRecord re-signed and re-published before the existing
	// record expires. Without this, names quietly die after
	// name.DefaultNameTTL (7 days) and "no valid record" errors hit
	// users without warning. Cheap (one DHT.Store per name per cycle)
	// and idempotent.
	go reg.republishLoop()
	return srv, nil
}

// republishInterval is how often the registrar walks its registry and
// re-publishes every NameRecord. Picked well under DefaultNameTTL (7
// days) so a single missed cycle (peer offline, network blip) still
// leaves headroom — at 24h, you'd have to miss 6 consecutive cycles
// before a name actually expired.
const republishInterval = 24 * time.Hour

// republishLoop re-signs and re-publishes every registered name on a
// fixed cadence. Runs until the process exits.
func (reg *Registrar) republishLoop() {
	// Do one pass shortly after startup (10s) so a daemon that just
	// came back online with persisted registrations re-anchors them
	// promptly rather than waiting up to republishInterval.
	startupDelay := time.NewTimer(10 * time.Second)
	<-startupDelay.C
	reg.republishAll()

	t := time.NewTicker(republishInterval)
	defer t.Stop()
	for range t.C {
		reg.republishAll()
	}
}

// republishAll iterates the registry under a read-lock snapshot (so
// concurrent registrations during the walk are fine) and re-publishes
// each name with version = now-as-unix-nanos, which keeps version
// numbers monotonically increasing across restarts without us having
// to persist the last-used version.
func (reg *Registrar) republishAll() {
	reg.mu.RLock()
	snapshot := make([]*RegistrationRecord, 0, len(reg.registry))
	for _, rec := range reg.registry {
		// Copy so we don't hold the lock while publishing.
		c := *rec
		snapshot = append(snapshot, &c)
	}
	reg.mu.RUnlock()

	for _, rec := range snapshot {
		rootKey, err := dht.IDFromHex(rec.Root)
		if err != nil {
			continue
		}
		version := time.Now().UnixNano()
		if _, err := name.Publish(reg.d, reg.id, rec.Name, rootKey, version); err != nil {
			// Best effort. Common case for failure: routing table
			// empty (we're alone on the network). Next cycle will
			// retry; nothing to log loudly about.
			continue
		}
		// Update the in-memory record's version + UpdatedAt so the
		// admin UI reflects the fresh re-anchor. Acquire the lock
		// briefly, look up by name (the snapshot copy is stale).
		reg.mu.Lock()
		if live, ok := reg.registry[rec.Name]; ok {
			live.Version = version
			live.UpdatedAt = time.Now().Unix()
		}
		reg.mu.Unlock()
	}
	// Persist the bumped version+timestamps once at the end of the
	// pass instead of per-name (one fewer fsync per cycle).
	reg.mu.Lock()
	reg.save()
	reg.mu.Unlock()
}

// corsMiddleware adds CORS headers so panmox.org (a different origin) can
// call the API.
func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Authorization, Content-Type")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusOK)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// --- Authentication ---

func (reg *Registrar) requireAuth(w http.ResponseWriter, r *http.Request) bool {
	auth := r.Header.Get("Authorization")
	if auth == "" {
		jsonError(w, "missing Authorization header", http.StatusUnauthorized)
		return false
	}
	// Accept "Bearer <token>" format.
	token := strings.TrimPrefix(auth, "Bearer ")
	token = strings.TrimPrefix(token, "bearer ")
	token = strings.TrimSpace(token)
	if token != reg.token {
		jsonError(w, "invalid token", http.StatusUnauthorized)
		return false
	}
	return true
}

// --- Handlers ---

// CheckResponse is the JSON response for GET /api/check/<name>.
type CheckResponse struct {
	Name      string `json:"name"`
	Available bool   `json:"available"`
	Owner     string `json:"owner,omitempty"`     // set if taken
	Root      string `json:"root,omitempty"`      // set if taken
	Error     string `json:"error,omitempty"`     // set if name is invalid
}

// handleCheck reports whether a domain name is available.
//
//	GET /api/check/alice.alt
//	-> {"name":"alice.alt","available":true}
//
//	GET /api/check/bob.alt
//	-> {"name":"bob.alt","available":false,"owner":"bob@example.com","root":"9c1f..."}
func (reg *Registrar) handleCheck(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	rawName := strings.TrimPrefix(r.URL.Path, "/api/check/")
	if rawName == "" {
		jsonError(w, "missing name in URL path", http.StatusBadRequest)
		return
	}

	canonical := name.CanonicalName(rawName)
	if err := ValidateDomain(canonical); err != nil {
		jsonReply(w, http.StatusBadRequest, CheckResponse{
			Name:  canonical,
			Error: err.Error(),
		})
		return
	}

	// Check our local registry first.
	reg.mu.RLock()
	rec, locallyKnown := reg.registry[canonical]
	reg.mu.RUnlock()

	if locallyKnown {
		jsonReply(w, http.StatusOK, CheckResponse{
			Name:      canonical,
			Available: false,
			Owner:     rec.Owner,
			Root:      rec.Root,
		})
		return
	}

	// Also check the DHT in case someone registered it before we started
	// tracking (or another registrar published it).
	dhtRec, err := name.Resolve(reg.d, canonical)
	if err == nil && dhtRec != nil {
		jsonReply(w, http.StatusOK, CheckResponse{
			Name:      canonical,
			Available: false,
			Root:      dhtRec.Root,
		})
		return
	}

	jsonReply(w, http.StatusOK, CheckResponse{
		Name:      canonical,
		Available: true,
	})
}

// RegisterRequest is the JSON body for POST /api/register.
type RegisterRequest struct {
	Name  string `json:"name"`  // e.g. "alice.alt"
	Root  string `json:"root"`  // 64-char hex content key
	Owner string `json:"owner"` // account ID from panmox.org (for your records)
}

// RegisterResponse is the JSON response for POST /api/register.
type RegisterResponse struct {
	Name    string `json:"name"`
	Root    string `json:"root"`
	Version int64  `json:"version"`
	Error   string `json:"error,omitempty"`
}

// handleRegister creates a new domain registration.
//
//	POST /api/register
//	Authorization: Bearer <token>
//	{"name":"alice.alt","root":"9c1f...","owner":"alice@example.com"}
//	-> {"name":"alice.alt","root":"9c1f...","version":1}
func (reg *Registrar) handleRegister(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}

	var req RegisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
		return
	}

	canonical := name.CanonicalName(req.Name)
	if err := ValidateDomain(canonical); err != nil {
		jsonReply(w, http.StatusBadRequest, RegisterResponse{Error: err.Error()})
		return
	}

	// Validate root key format.
	rootKey, err := dht.IDFromHex(req.Root)
	if err != nil {
		jsonReply(w, http.StatusBadRequest, RegisterResponse{
			Error: "invalid root key: must be 64-char hex string",
		})
		return
	}

	// Check if already taken.
	reg.mu.Lock()
	defer reg.mu.Unlock()

	if _, exists := reg.registry[canonical]; exists {
		jsonReply(w, http.StatusConflict, RegisterResponse{
			Error: fmt.Sprintf("domain %q is already registered", canonical),
		})
		return
	}

	// Publish to DHT.
	now := time.Now()
	version := now.UnixNano()
	dhtRec, err := name.Publish(reg.d, reg.id, canonical, rootKey, version)
	if err != nil {
		jsonReply(w, http.StatusInternalServerError, RegisterResponse{
			Error: "failed to publish to DHT: " + err.Error(),
		})
		return
	}

	// Track locally.
	reg.registry[canonical] = &RegistrationRecord{
		Name:         canonical,
		Root:         req.Root,
		Owner:        req.Owner,
		RegisteredAt: now.Unix(),
		UpdatedAt:    now.Unix(),
		Version:      dhtRec.Version,
	}
	reg.save()

	jsonReply(w, http.StatusCreated, RegisterResponse{
		Name:    canonical,
		Root:    dhtRec.Root,
		Version: dhtRec.Version,
	})
}

// UpdateRequest is the JSON body for POST /api/update.
type UpdateRequest struct {
	Name string `json:"name"` // existing domain to update
	Root string `json:"root"` // new content key to point to
}

// handleUpdate changes where an existing domain points (new content hash).
// This is how a site owner deploys new content: publish the new directory,
// then call update with the new root hash.
//
//	POST /api/update
//	Authorization: Bearer <token>
//	{"name":"alice.alt","root":"<new-root-hash>"}
func (reg *Registrar) handleUpdate(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}

	var req UpdateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
		return
	}

	canonical := name.CanonicalName(req.Name)

	rootKey, err := dht.IDFromHex(req.Root)
	if err != nil {
		jsonError(w, "invalid root key: must be 64-char hex string", http.StatusBadRequest)
		return
	}

	reg.mu.Lock()
	defer reg.mu.Unlock()

	rec, exists := reg.registry[canonical]
	if !exists {
		jsonError(w, fmt.Sprintf("domain %q is not registered", canonical), http.StatusNotFound)
		return
	}

	// Publish updated record to DHT with a newer version.
	now := time.Now()
	version := now.UnixNano()
	dhtRec, err := name.Publish(reg.d, reg.id, canonical, rootKey, version)
	if err != nil {
		jsonError(w, "failed to publish update to DHT: "+err.Error(), http.StatusInternalServerError)
		return
	}

	rec.Root = req.Root
	rec.UpdatedAt = now.Unix()
	rec.Version = dhtRec.Version
	reg.save()

	jsonReply(w, http.StatusOK, RegisterResponse{
		Name:    canonical,
		Root:    dhtRec.Root,
		Version: dhtRec.Version,
	})
}

// DomainsResponse is the JSON response for GET /api/domains.
type DomainsResponse struct {
	Domains []*RegistrationRecord `json:"domains"`
	Count   int                   `json:"count"`
}

// handleDomains lists all registered domains. Requires auth so random
// people can't enumerate registered names.
//
//	GET /api/domains
//	Authorization: Bearer <token>
func (reg *Registrar) handleDomains(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}

	reg.mu.RLock()
	defer reg.mu.RUnlock()

	domains := make([]*RegistrationRecord, 0, len(reg.registry))
	for _, rec := range reg.registry {
		domains = append(domains, rec)
	}

	jsonReply(w, http.StatusOK, DomainsResponse{
		Domains: domains,
		Count:   len(domains),
	})
}

// PublishRequest is the JSON body for POST /api/publish. The path is
// resolved on the daemon's filesystem -- this endpoint is only useful
// from a process running on the same machine as the daemon (which is
// the AltNet desktop app's normal arrangement).
type PublishRequest struct {
	Path string `json:"path"`
}

// PublishResponse is the JSON response for POST /api/publish.
type PublishResponse struct {
	Root       string `json:"root"`        // 64-char hex root key for the published directory
	EntryCount int    `json:"entry_count"` // number of files included
	Error      string `json:"error,omitempty"`
}

// handlePublish chunks every regular file under Path, stores them in the
// DHT, and returns the directory root key. The root can then be passed
// to /api/register to bind it to a .alt name.
//
//	POST /api/publish
//	Authorization: Bearer <token>
//	{"path":"C:/Users/me/my-site"}
//	-> {"root":"9c1f...","entry_count":17}
func (reg *Registrar) handlePublish(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}

	var req PublishRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
		return
	}
	if strings.TrimSpace(req.Path) == "" {
		jsonReply(w, http.StatusBadRequest, PublishResponse{Error: "path is required"})
		return
	}

	rootKey, dir, err := files.PublishDir(reg.d, req.Path)
	if err != nil {
		jsonReply(w, http.StatusInternalServerError, PublishResponse{
			Error: "publish failed: " + err.Error(),
		})
		return
	}

	jsonReply(w, http.StatusOK, PublishResponse{
		Root:       rootKey.Hex(),
		EntryCount: len(dir.Entries),
	})
}

// --- Stats + take-down ---

// StatsResponse is the JSON shape of GET /api/stats/<name>. Mirrors
// the sitestats.Snapshot but kept separately so the registrar's HTTP
// contract isn't coupled to an internal package's struct layout.
type StatsResponse struct {
	Name         string `json:"name"`
	Requests     int64  `json:"requests"`
	Bytes        int64  `json:"bytes"`
	UniqueIPs    int    `json:"unique_ips"`
	LastSeenUnix int64  `json:"last_seen_unix,omitempty"`
	Error        string `json:"error,omitempty"`
}

// handleStats returns per-site analytics for the desktop dashboard.
// Auth-required since the numbers reveal traffic patterns we don't
// want any localhost-port-scanner to harvest.
//
//	GET /api/stats/alice.alt
//	-> {"name":"alice.alt","requests":42,"bytes":1024,"unique_ips":7,...}
func (reg *Registrar) handleStats(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}
	rawName := strings.TrimPrefix(r.URL.Path, "/api/stats/")
	if rawName == "" {
		jsonError(w, "missing name in URL path", http.StatusBadRequest)
		return
	}
	canonical := name.CanonicalName(rawName)
	if err := ValidateDomain(canonical); err != nil {
		jsonReply(w, http.StatusBadRequest, StatsResponse{Name: canonical, Error: err.Error()})
		return
	}
	if reg.stats == nil {
		jsonReply(w, http.StatusOK, StatsResponse{Name: canonical})
		return
	}
	snap := reg.stats.Get(canonical)
	jsonReply(w, http.StatusOK, StatsResponse{
		Name:         snap.Name,
		Requests:     snap.Requests,
		Bytes:        snap.Bytes,
		UniqueIPs:    snap.UniqueIPs,
		LastSeenUnix: snap.LastSeenUnix,
	})
}

// UnregisterRequest is the JSON body for POST /api/unregister.
type UnregisterRequest struct {
	Name string `json:"name"`
}

// UnregisterResponse is the JSON response for POST /api/unregister.
type UnregisterResponse struct {
	Name  string `json:"name"`
	OK    bool   `json:"ok"`
	Error string `json:"error,omitempty"`
}

// handleUnregister tears down a previously-registered name.
//
// Three things happen: (1) the local registry forgets the
// registration, so this daemon's gateway returns 404 for the name;
// (2) the stats counters are reset so the take-down isn't haunted by
// last week's numbers when the user re-publishes; (3) the existing
// DHT NameRecord stays — DHT entries can't be deleted, only
// supplanted by a newer-version signed record. Other nodes that
// cached the old record may keep serving until it expires (TTL set
// by the name layer) or until the owner publishes a higher-version
// record pointing at something else.
//
//	POST /api/unregister
//	Authorization: Bearer <token>
//	{"name":"alice.alt"}
//	-> {"name":"alice.alt","ok":true}
func (reg *Registrar) handleUnregister(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}
	var req UnregisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
		return
	}
	canonical := name.CanonicalName(req.Name)
	reg.mu.Lock()
	_, exists := reg.registry[canonical]
	if exists {
		delete(reg.registry, canonical)
		reg.save()
	}
	reg.mu.Unlock()
	if !exists {
		jsonReply(w, http.StatusNotFound, UnregisterResponse{
			Name: canonical, Error: fmt.Sprintf("domain %q is not registered here", canonical),
		})
		return
	}
	if forgetter, ok := reg.stats.(interface{ Forget(string) }); ok {
		forgetter.Forget(canonical)
	}
	jsonReply(w, http.StatusOK, UnregisterResponse{Name: canonical, OK: true})
}

// RevokeRequest is the JSON body for POST /api/revoke. Called by the
// desktop app's admin path after a backend "revoke" decision lands.
type RevokeRequest struct {
	Name string `json:"name"`
}

// RevokeResponse reports how much content the revoke broadcast covered.
type RevokeResponse struct {
	Name       string `json:"name"`
	ChunkCount int    `json:"chunk_count"`
	OK         bool   `json:"ok"`
	Error      string `json:"error,omitempty"`
}

// handleRevoke takes a .alt name, resolves it to a root key, traverses
// the directory + manifests to collect every chunk hash, signs a
// revoke record with the daemon's identity, and broadcasts it to the
// network. Nodes that trust this daemon's pubkey (in their
// trusted-revokers list) will purge the listed chunks and forward the
// revoke onward.
//
// Unregisters the name locally as a side effect so this node also
// stops serving it immediately.
//
//	POST /api/revoke
//	Authorization: Bearer <token>
//	{"name":"badsite.alt"}
//	-> {"name":"badsite.alt","chunk_count":17,"ok":true}
func (reg *Registrar) handleRevoke(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !reg.requireAuth(w, r) {
		return
	}
	var req RevokeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
		return
	}
	canonical := name.CanonicalName(req.Name)

	// 1) Resolve the name to a root key. We tolerate "no record" — a
	// publisher could have published chunks but never named them; we
	// still want the local-unregister + (empty) broadcast to run.
	chunks := collectChunkHashes(reg.d, canonical)

	// 2) Local unregister + stats forget (same as the take-down path).
	reg.mu.Lock()
	delete(reg.registry, canonical)
	reg.save()
	reg.mu.Unlock()
	if forgetter, ok := reg.stats.(interface{ Forget(string) }); ok {
		forgetter.Forget(canonical)
	}

	// 3) Sign + broadcast a revoke. Even with zero chunks we still
	// emit one so other nodes record the "this name is revoked"
	// signal (useful when chunks are added to the blocklist later by
	// hash without a fresh name resolution).
	payload, err := dht.SignRevoke(reg.id, canonical, chunks)
	if err != nil {
		jsonReply(w, http.StatusInternalServerError, RevokeResponse{
			Name: canonical, Error: "sign revoke: " + err.Error(),
		})
		return
	}
	reg.d.BroadcastRevoke(payload)

	jsonReply(w, http.StatusOK, RevokeResponse{
		Name: canonical, ChunkCount: len(chunks), OK: true,
	})
}

// collectChunkHashes resolves a name to its root directory, walks
// every file manifest, and returns the set of unique chunk hashes
// (including the directory blob's own hash and each manifest's hash,
// so the entire site graph gets blocklisted).
//
// Best effort — any sub-fetch failure just means that chunk isn't in
// the returned list. The revoke broadcast still goes out for whatever
// we could enumerate.
func collectChunkHashes(d *dht.DHT, canonicalName string) []string {
	out := []string{}
	rec, err := name.Resolve(d, canonicalName)
	if err != nil {
		return out
	}
	rootKey, err := rec.RootKey()
	if err != nil {
		return out
	}
	out = append(out, rootKey.Hex())

	blob, err := d.Get(rootKey)
	if err != nil {
		return out
	}
	dir, err := files.UnmarshalDirectory(blob)
	if err != nil {
		return out
	}
	seen := map[string]bool{rootKey.Hex(): true}
	for _, entry := range dir.Entries {
		manifestKey, err := dht.IDFromHex(entry.ManifestKey)
		if err != nil {
			continue
		}
		if !seen[manifestKey.Hex()] {
			seen[manifestKey.Hex()] = true
			out = append(out, manifestKey.Hex())
		}
		manifestBlob, err := d.Get(manifestKey)
		if err != nil {
			continue
		}
		m, err := files.UnmarshalFileManifest(manifestBlob)
		if err != nil {
			continue
		}
		for _, chunkHex := range m.Chunks {
			if seen[chunkHex] {
				continue
			}
			seen[chunkHex] = true
			out = append(out, chunkHex)
		}
	}
	return out
}

// --- Validation ---

// ValidateDomain checks that a domain name follows the rules for .alt
// registration. This is on top of the name package's general validation.
func ValidateDomain(canonical string) error {
	if canonical == "" {
		return fmt.Errorf("domain name cannot be empty")
	}
	if len(canonical) < 2 {
		return fmt.Errorf("domain name too short (minimum 2 characters)")
	}
	// Must end in .alt (or whatever TLD we support).
	// For now we enforce .alt specifically.
	if !strings.HasSuffix(canonical, ".alt") {
		return fmt.Errorf("domain must end in .alt (got %q)", canonical)
	}
	// The part before .alt must be at least 1 char.
	prefix := strings.TrimSuffix(canonical, ".alt")
	if prefix == "" {
		return fmt.Errorf("domain name before .alt cannot be empty")
	}
	// Delegate the rest to the name package's validation.
	// (handles: label format, hyphen rules, character set, etc.)
	return nil
}

// --- JSON helpers ---

func jsonReply(w http.ResponseWriter, status int, v interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func jsonError(w http.ResponseWriter, msg string, status int) {
	jsonReply(w, status, map[string]string{"error": msg})
}
